name = "nixpkgs-reviewd"
main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

workers_dev = true
compatibility_date = "2022-02-02"

[build]
command = "npm run build"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[logs]
enabled = true
invocation_logs = false
