# This is a basic workflow to help you get started with Actions

name: finish fast

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
      - run: echo ok

